---
title: "biomass.Rmd"
author: "HM Putnam, AS Huffmyer"
date: "10/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")

# load packages
library(tidyverse)
library(plotrix)

```

```{r }
#Read in biomass data
Data <- read.csv("data/biomass_data.csv")
Data <- na.omit(Data)

# calculated mass per ml
#different volumes for sym (4ml) and host (5ml)
sym <- 4
host <- 5

#Load tissue homogenate volume
homog_vol <- read.csv("data/homogenate_vols.csv", header=TRUE)

# Load Surface area data
sa <- read.csv("data/TPC_surface.area.calc.csv")

# Coral sample metadata
metadata <- read_csv("data/metadata_POC_TPC.csv")

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vol) %>%
  full_join(sa)

#Standardize for volume input
Data <- Data %>%
  mutate(dry.pan.mass.g.ml = case_when(partner=="Sym" ~ dry.pan.mass.g/sym, partner=="Host" ~dry.pan.mass.g/host),
         burnt.pan.mass.g.ml = case_when(partner=="Sym" ~ burnt.pan.mass.g/sym, partner=="Host" ~burnt.pan.mass.g/host))

# Standardize for the total homogenate volume
Data <- left_join(Data, homog_vol)  %>%
  mutate(dry.pan.mass.g.vol.corr = dry.pan.mass.g.ml*homog_vol_ml, 
         burnt.pan.mass.g.vol.corr = burnt.pan.mass.g.ml*homog_vol_ml)


# Calculate Dry Biomass
dw <- left_join(Data, metadata) %>%
  mutate(dry.bioimass.g = (dry.pan.mass.g.vol.corr - initial.mass.g),
         DW.mg.cm2 = ((dry.bioimass.g)*1000) / surface.area.cm2)


# Calculate AFDW
afdw <- left_join(Data, metadata) %>%
  mutate(dry.bioimass.g = (dry.pan.mass.g.vol.corr - burnt.pan.mass.g.vol.corr),
         AFDW.mg.cm2 = ((dry.bioimass.g)*1000) / surface.area.cm2)


```

Output biomass data to .csv.  

```{r}
afdw<-afdw %>%
  group_by(fragment_ID, partner)%>%
  summarise(AFDW.mg.cm2=mean(AFDW.mg.cm2))%>%
  left_join(.,metadata)%>% #add metadata back into file
  select(fragment_ID, partner, Morphology, AFDW.mg.cm2)

dw<-dw %>% 
  group_by(fragment_ID, partner)%>%
  summarise(DW.mg.cm2=mean(DW.mg.cm2))%>%
  left_join(.,metadata)%>% #add metadata back into file
  select(fragment_ID, partner, Morphology, DW.mg.cm2) 
  
output<-left_join(afdw,dw)%>%
  write_csv(path = "output/biomass.csv")
```

```{r}
#summarize Dry Biomass mean and sem by site, species, and partner and plot

dw %>% 
  group_by(Morphology, partner)%>%
  summarise(mean.value = mean(DW.mg.cm2), se = std.error(DW.mg.cm2)) %>%
  ggplot(aes(x = Morphology, y = mean.value, group = Morphology, color = partner))+
  ylab("DW mg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = Morphology,, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)

# Plot all data points with mean ± se
dw %>%
  ggplot(aes(x = Morphology, y = DW.mg.cm2, color = Morphology)) +
  scale_color_manual(name="Morphology", values=c("orange","black", "cyan"))+
  #coord_cartesian(ylim = c(0, 1.8))+
  labs(x = "", y = expression("Dry Biomass mg"~cm^{-2})) +
  geom_jitter(width = 0.1) +                                            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black") +           # Plot mean
  theme_bw(base_size = 12)+
  facet_wrap("partner")


```

```{r}

afdw %>% 
  group_by(Morphology, partner)%>%
  summarise(mean.value = mean(AFDW.mg.cm2), se = std.error(AFDW.mg.cm2)) %>%
  ggplot(aes(x = Morphology, y = mean.value, group = Morphology, color = partner))+
  ylab("AFDW mg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = Morphology,, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)

# Plot all data points with mean ± se
afdw %>%
  ggplot(aes(x = Morphology, y = AFDW.mg.cm2, color = Morphology)) +
  scale_color_manual(name="Morphology", values=c("orange","black", "cyan"))+
  #coord_cartesian(ylim = c(0, 5))+
  labs(x = "", y = expression("AFDW mg"~cm^{-2})) +
  geom_jitter(width = 0.1) +                                            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black") +           # Plot mean
  theme_bw(base_size = 12)+
  facet_wrap("partner")

```


 
