---
title: "Untitled"
author: "HM Putnam"
date: "10/1/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Libraries
```{r}
#https://stackoverflow.com/questions/63653396/specific-number-of-points-within-each-polygon-of-a-shape-in-r
library(sf)
library(ggplot2)
library(tidyverse)

```

#Read in shp files
```{r}

#geomorphic shape file extracted from Allen Coral Atlas
Moorea <- st_read("data/Moorea_polygons/geomorphic.shp")
#polygons outlined from around the LTER site GPS points
LTER1 <- st_read("data/Moorea_polygons/LTER1_small_boundary.shp")
LTER2 <- st_read("data/Moorea_polygons/LTER2_small_boundary.shp")
LTER3 <- st_read("data/Moorea_polygons/LTER3_small_boundary.shp")
LTER4 <- st_read("data/Moorea_polygons/LTER4_small_boundary.shp")
LTER5 <- st_read("data/Moorea_polygons/LTER5_small_boundary.shp")
LTER6 <- st_read("data/Moorea_polygons/LTER6_small_boundary.shp")

#north shore potential site polygons extracted from Allen Atlas
#N for everything on the island, can change after if we see problem during run
NZ1 <- st_read("data/Moorea_polygons/NZ1_boundary.shp")
NZ2 <- st_read("data/Moorea_polygons/NZ2_boundary.shp")
NZ3 <- st_read("data/Moorea_polygons/NZ3_boundary.shp")
NZ4 <- st_read("data/Moorea_polygons/NZ4_boundary.shp")
NZ5 <- st_read("data/Moorea_polygons/NZ5_boundary.shp")
NZ6 <- st_read("data/Moorea_polygons/NZ6_boundary.shp")
NZ7 <- st_read("data/Moorea_polygons/NZ7_boundary.shp")
NZ8 <- st_read("data/Moorea_polygons/NZ8_boundary.shp")
NZ9 <- st_read("data/Moorea_polygons/NZ9_boundary.shp")
NZ10 <- st_read("data/Moorea_polygons/NZ10_boundary.shp")
NZ11 <- st_read("data/Moorea_polygons/NZ11_boundary.shp")
NZ12 <- st_read("data/Moorea_polygons/NZ12_boundary.shp")
NZ13 <- st_read("data/Moorea_polygons/NZ13_boundary.shp")
NZ14 <- st_read("data/Moorea_polygons/NZ14_boundary.shp")
NZ15 <- st_read("data/Moorea_polygons/NZ15_boundary.shp")
NZ16 <- st_read("data/Moorea_polygons/NZ16_boundary.shp")
NZ17 <- st_read("data/Moorea_polygons/NZ17_boundary.shp")
NZ18 <- st_read("data/Moorea_polygons/NZ18_boundary.shp")

#polygons made available by the MCR
#MCR <- st_read("data/Moorea_polygons/LTER_boundary.shp")

#Moorea PGEM site polygons extracted from Allen Atlas using the PGEM map
PGEM1 <- st_read("data/Moorea_polygons/PGEM1_boundary.shp")
PGEM2 <- st_read("data/Moorea_polygons/PGEM2_boundary.shp")
PGEM3 <- st_read("data/Moorea_polygons/PGEM3_boundary.shp")
PGEM4 <- st_read("data/Moorea_polygons/PGEM4_boundary.shp")
PGEM5 <- st_read("data/Moorea_polygons/PGEM5_boundary.shp")
PGEM6 <- st_read("data/Moorea_polygons/PGEM6_boundary.shp")
PGEM7 <- st_read("data/Moorea_polygons/PGEM7_boundary.shp")
PGEM8 <- st_read("data/Moorea_polygons/PGEM8_boundary.shp")
```

#generate random points within the available polygons
```{r}
# st_sample needs a vector telling it how many samples for each site polygon
#  here we're using # for each polygon

NZ1.samples <- st_sample(NZ1, 1, type = "random")
NZ2.samples <- st_sample(NZ2, 1, type = "random")
NZ3.samples <- st_sample(NZ3, 1, type = "random")
NZ4.samples <- st_sample(NZ4, 1, type = "random")
NZ5.samples <- st_sample(NZ5, 1, type = "random")
NZ6.samples <- st_sample(NZ6, 1, type = "random")
NZ7.samples <- st_sample(NZ7, 1, type = "random")
NZ8.samples <- st_sample(NZ8, 1, type = "random")
NZ9.samples <- st_sample(NZ9, 1, type = "random")
NZ10.samples <- st_sample(NZ10, 1, type = "random")
NZ11.samples <- st_sample(NZ11, 1, type = "random")
NZ12.samples <- st_sample(NZ12, 1, type = "random")
NZ13.samples <- st_sample(NZ13, 1, type = "random")
NZ14.samples <- st_sample(NZ14, 1, type = "random")
NZ15.samples <- st_sample(NZ15, 1, type = "random")
NZ16.samples <- st_sample(NZ16, 1, type = "random")
NZ17.samples <- st_sample(NZ17, 1, type = "random")
NZ18.samples <- st_sample(NZ18, 1, type = "random")

#create a buffer space around the points so they must be Xm or Xkm away from each other
#https://stackoverflow.com/questions/64391369/how-to-specify-a-minimum-distance-between-points-in-sfst-sample
#Random points

# N2.samples <- st_sample(N2, size = 20, type="random")
# N2.samples <- st_sf(N2.samples)
# 
# original <- N2.samples # for comparison later :)
# 
# 
# i <- 1 # iterator start
# 
# buffer_size <- 1800 # minimal distance to be enforced (in units of your CRS)
# 
# repeat( {
#   #  create buffer around i-th point
#   buffer <- st_buffer(N2.samples[i,], buffer_size ) 
#   
#   offending <- N2.samples %>%  # start with the intersection of master points... 
#     st_intersects(buffer, sparse = F) # ... and the buffer, as a vector
#   
#   # i-th point is not really offending - it is the origin (not to be excluded)
#   offending[i] <- FALSE
#   
#   # if there are any offending points left - re-assign the master points, 
#   # with the offending ones excluded / this is the main pruning part :)
#   N2.samples <- N2.samples[!offending,] 
#   
#   if ( i >= nrow(N2.samples)) {
#     # the end was reached; no more points to process
#     break 
#   } else {
#     # rinse & repeat
#     i <- i + 1 
#   }
#   
# } )
# 
# 
# plot(original, pch = 4, col = "grey25") # result of the st_sample()
# 
# plot(N2.samples, pch = 4, col = "red", add = T) # pruned points
# 




```

#plot Moorea, PGEM, LTER, Available, and selected sites
```{r}
MooreaSitemap <- ggplot() + geom_sf(data = Moorea) +
  #plot extracted LTER polygons
  geom_sf(data = LTER1, aes(fill="MCR")) +
  geom_sf(data = LTER2, aes(fill="MCR")) +
  geom_sf(data = LTER3, aes(fill="MCR")) +
  geom_sf(data = LTER4, aes(fill="MCR")) +
  geom_sf(data = LTER5, aes(fill="MCR")) +
  geom_sf(data = LTER6, aes(fill="MCR")) +
  #plot extracted PGEM polygons
  geom_sf(data = PGEM1, aes(fill="PGEM")) +
  geom_sf(data = PGEM2, aes(fill="PGEM")) +
  geom_sf(data = PGEM3, aes(fill="PGEM")) +
  geom_sf(data = PGEM4, aes(fill="PGEM")) +
  geom_sf(data = PGEM5, aes(fill="PGEM")) +
  geom_sf(data = PGEM6, aes(fill="PGEM")) +
  geom_sf(data = PGEM7, aes(fill="PGEM")) +
  geom_sf(data = PGEM8, aes(fill="PGEM")) +
  #plot extracted available Sites polygons
  geom_sf(data = NZ1, aes(fill="Available")) +
  geom_sf(data = NZ2, aes(fill="Available")) +
  geom_sf(data = NZ3, aes(fill="Available")) +
  geom_sf(data = NZ4, aes(fill="Available")) +
  geom_sf(data = NZ5, aes(fill="Available")) +
  geom_sf(data = NZ6, aes(fill="Available")) +
  geom_sf(data = NZ7, aes(fill="Available")) +
  geom_sf(data = NZ8, aes(fill="Available")) +
  geom_sf(data = NZ9, aes(fill="Available")) +
  geom_sf(data = NZ10, aes(fill="Available")) +
  geom_sf(data = NZ11, aes(fill="Available")) +
  geom_sf(data = NZ12, aes(fill="Available")) +
  geom_sf(data = NZ13, aes(fill="Available")) +
  geom_sf(data = NZ14, aes(fill="Available")) +
  geom_sf(data = NZ15, aes(fill="Available")) +
  geom_sf(data = NZ16, aes(fill="Available")) +
  geom_sf(data = NZ17, aes(fill="Available")) +
  geom_sf(data = NZ18, aes(fill="Available")) +
  #plot randomly selected site points
  geom_sf(data = NZ1.samples, aes(color = "Sites")) +
  geom_sf(data = NZ2.samples, aes(color = "Sites")) +
  geom_sf(data = NZ3.samples, aes(color = "Sites")) +
  geom_sf(data = NZ4.samples, aes(color = "Sites")) +
  geom_sf(data = NZ5.samples, aes(color = "Sites")) +
  geom_sf(data = NZ6.samples, aes(color = "Sites")) +
  geom_sf(data = NZ7.samples, aes(color = "Sites")) +
  geom_sf(data = NZ8.samples, aes(color = "Sites")) +
  geom_sf(data = NZ9.samples, aes(color = "Sites")) +
  geom_sf(data = NZ10.samples, aes(color = "Sites")) +
  geom_sf(data = NZ11.samples, aes(color = "Sites")) +
  geom_sf(data = NZ12.samples, aes(color = "Sites")) +
  geom_sf(data = NZ13.samples, aes(color = "Sites")) +
  geom_sf(data = NZ14.samples, aes(color = "Sites")) +
  geom_sf(data = NZ15.samples, aes(color = "Sites")) +
  geom_sf(data = NZ16.samples, aes(color = "Sites")) +
  geom_sf(data = NZ17.samples, aes(color = "Sites")) +
  geom_sf(data = NZ18.samples, aes(color = "Sites")) +
  scale_fill_manual(name='Areas',
                     breaks=c('MCR', 'PGEM', 'Sites', 'Available'),
                     values=c('MCR'='yellow', 'PGEM'='black',
                              'Available'='green','Sites'='red')) +
  theme_bw()

pdf("data/Moorea_polygons/transect_sites.pdf")
MooreaSitemap
dev.off()
```
#Write out randomly selected site coordinates
```{r}

st_write(NZ1.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords1.csv", delete_dsn=TRUE)
st_write(NZ2.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords2.csv", delete_dsn=TRUE)
st_write(NZ3.samples, layer_options = "GEOMETRY=AS_XY","transect.site.coords3.csv", delete_dsn=TRUE)
st_write(NZ4.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords4.csv", delete_dsn=TRUE)
st_write(NZ5.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords5.csv", delete_dsn=TRUE)
st_write(NZ6.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords6.csv", delete_dsn=TRUE)
st_write(NZ7.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords7.csv", delete_dsn=TRUE)
st_write(NZ8.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords8.csv", delete_dsn=TRUE)
st_write(NZ9.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords9.csv", delete_dsn=TRUE)
st_write(NZ10.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords10.csv", delete_dsn=TRUE)
st_write(NZ11.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords11.csv", delete_dsn=TRUE)
st_write(NZ12.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords12.csv", delete_dsn=TRUE)
st_write(NZ13.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords13.csv", delete_dsn=TRUE)
st_write(NZ14.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords14.csv", delete_dsn=TRUE)
st_write(NZ15.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords15.csv", delete_dsn=TRUE)
st_write(NZ16.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords16.csv", delete_dsn=TRUE)
st_write(NZ17.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords17.csv", delete_dsn=TRUE)
st_write(NZ18.samples, layer_options = "GEOMETRY=AS_XY", "transect.site.coords18.csv", delete_dsn=TRUE)

#combine the points into one dataframe
Sites <- list.files() %>%
 str_subset("\\.csv$")  %>%
  lapply(read_csv) %>% 
  bind_rows

colnames(Sites) <-c("long", "lat")
#but this puts it in order 1,11,12,13,14... instead of 1-18
#Sites$site.name <- c(paste0("site"," ", rep(1:nrow(Sites),each = 1)))
#this puts it in the correct order, but is hard coded, so is only for 18 sites
Sites$site.name <- c("site1","site10", "site11", "site12","site13", "site14", 
                     "site15","site16", "site17", "site18", "site2", "site3",
                     "site4", "site5", "site6","site7", "site8", "site9")

write_csv(Sites,"data/Moorea_polygons/sites/transect.site.coords.csv")
```

