---
title: "size_class_Relative_abundance"
author: "Pierrick"
date: "2025-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggmap)
#library(ggsn)
library(gridExtra)
library(cowplot)
library(dplyr)
library(tidyr)
library(forcats)
library(patchwork)
```

```{r}
#load size data

size_data <- read.csv ("data/20250620_Size_class_TPC.csv")
#code to change name of column in size_data_average
colnames(size_data)[1] <- "Coral_ID"
#POC-324-T6 no photo available
#POC-166-T3 excluded for bad photo
size_data <- size_data %>%
  filter(Coral_ID != "POC-324-T6") %>%
  filter(Coral_ID != "POC-166-T3")


#load haplotype/ species data 
species_data <- read.csv ("../Sanger_Data/Transect_Seqs/Poc_Transect_Seqs.csv")
species_data <- species_data %>%
  filter(Coral_ID != "POC-324-T6") %>%
  filter(Coral_ID != "POC-166-T3")

```

```{r}
# Calculate the average of the Diameter columns
size_data <- size_data %>%
  mutate(Average.Diameter.cm = rowMeans(select(., Diameter.1, Diameter.2, Diameter.3), na.rm = TRUE)) %>%
  select(-Transect)

```

```{r}
# remove colum that i dont want in species_data 
#species_data_clean <- species_data %>% select(-Date, -Site, -Transect, -SeqRun, -mtORF.For.Name, #-mtORF.Rev.Name, -X20240619.Status, -PocHistone.ID, -Lifestage, -Size)



#code to merge the size with the species from the file Poc_Transect_Seqs 
data <- left_join(species_data, size_data, by = "Coral_ID")

#now i want to put a color on for each species
cols.species <- c(
  "P. tuahiniensis" = "#D55E00",
  "P. meandrina P. grandis" = "#0072B2",
  "P. verrucosa" = "#E69F00",
  "P. grandis" = "#56B4E9",
  "P. cf effusa" = "#009E73",
  "P. acuta" = "#e63946",
  "P. meandrina" = "#CC79A7"
)


# Define the break points for the categories
breaks <- c(0, 5, 14, Inf)  # Adjust these values as needed
labels <- c( "0cm-5cm", ">5cm-14cm", ">14cm")  # Category labels

# Create a new column for SizeClass based on Average.Diameter.cm
data$SizeClass <- cut(data$Average.Diameter.cm, 
                      breaks = breaks, 
                      labels = labels, 
                      right = FALSE)  


```

```{r}
#creation of the graph with species and size 
#filtering the data to exclude NAs
data_sp <- data %>%
  filter(X20240619.Status !="Fail")

#calculate relative abundance by Transect, SizeClass, species
relative_abundance.manava <- data_sp %>%
  group_by(Transect, SizeClass, Species.ID) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(Transect, SizeClass) %>%
  mutate(Relative_Abundance = Count / sum(Count)) %>%
  ungroup()

relative_abundance.manava$Transect <- factor(relative_abundance.manava$Transect, levels = c("1", "2", "3", "4", "5", "6", "7"))

# Calculate sample size for each Site and LifeStage
#sample_sizes_manava <- relative_abundance.manava %>%
#  group_by(Transect, LifeStage) %>%
#  summarise(Sample_Size = sum(Count), .groups = "drop")

fig1 <- ggplot(relative_abundance.manava, aes(x = Transect, y = Relative_Abundance, fill = Species.ID)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~ SizeClass, ncol = 5) +
  scale_fill_manual(values = cols.species) 

fig1 
```

```{r}

#calculate relative abundance by SizeClass, species
relative_abundance.manava <- data_sp %>%
  group_by(Site.x, SizeClass, Species.ID) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(SizeClass) %>%
  mutate(Relative_Abundance = Count / sum(Count)) %>%
  ungroup()


# Calculate sample size for each Site and LifeStage
#sample_sizes_manava <- relative_abundance.manava %>%
#  group_by(Transect, LifeStage) %>%
#  summarise(Sample_Size = sum(Count), .groups = "drop")

fig2 <- ggplot(relative_abundance.manava, aes(x = Site.x, y = Relative_Abundance, fill = Species.ID)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~ SizeClass, ncol = 3) +
  scale_fill_manual(values = cols.species) 

fig2

fig3 <- ggplot(relative_abundance.manava, aes(x = Site.x, y = Relative_Abundance, fill = Species.ID)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~ SizeClass, ncol = 1, strip.position = "left") +  # Fixed strip.position
  scale_fill_manual(values = cols.species) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    strip.placement = "outside",
    strip.background = element_blank(),
    panel.spacing = unit(0.2, "lines"),
    axis.text.y = element_blank()  # Fixed comma and placement
  ) +
  labs(x = NULL)

fig3
```

```{r}
#calculate relative abundance by SizeClass, species
relative_abundance.manava <- data_sp %>%
  group_by(Site.x,Species.ID) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  mutate(Relative_Abundance = Count / sum(Count)) %>%
  ungroup()


# Calculate sample size for each Site and LifeStage
#sample_sizes_manava <- relative_abundance.manava %>%
#  group_by(Transect, LifeStage) %>%
#  summarise(Sample_Size = sum(Count), .groups = "drop")

fig4 <- ggplot(relative_abundance.manava, aes(x = Site.x, y = Relative_Abundance, fill = Species.ID)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = cols.species) 

fig4
```

Arrange figures
```{r}
#add in one figure the figure 3 and 4

fig5 <- (fig3 + fig4) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

fig5
```
```{r}
#adding the code for the quadrats data and make the plot 
#loading data
library(tidyverse)

#load the quadrats data 100 points quadrats analysis 
data_quadrats <- read.csv("data/100_quadrats_data_TPC.csv")

#reformatting the column name 
data_quadrats$Name <- gsub(".JPG", "", data_quadrats$Name)
data_quadrats$Name <- gsub("-_", "_", data_quadrats$Name)

#remove the 100_TPC_ on the name of each data point when the data got extracted on CoralNet
data_quadrats$Name<- gsub("100_TPC_", "", data_quadrats$Name)

#separe the Quadrats number, site, transect and num of the 
data_quadrats <- data_quadrats %>% separate(Name, c("Quad", "Site", "Transect"))
unique(data_quadrats$Transect)

#T3 <- data_quadrats %>% filter(str_detect(Transect, "T3"))
#T4 <- data_quadrats %>% filter(str_detect(Transect, "T4"))
#T5 <- data_quadrats %>% filter(str_detect(Transect, "T5"))

#data.subset <- rbind(T3, T4, T5)

counts <- data.subset %>%
  group_by(Transect, Quad) %>%
  summarise(Count = n()) 
#data with 100 points
RA.100 <- data.subset %>%
  group_by(Label) %>%
  summarise(Count = n()) %>% 
  mutate(freq=Count/sum(Count))

RA.100$Site <- "Manava"

unique(RA.100$Label)

colors <- c("Acropora"="yellow",  "AlgalTurf"="lightgreen", "Astrea" = "lightyellow", "D_coral" = "gray",    "Goniastrea" ="lightblue", "Halimeda" ="green",  "MAL"="lightgreen", "Leptoseris" = "cyan", "Monti"="purple", "Pocill" = "coral", "Porites" ="brown", "Sand"= "tan", "Tur_orn" = "darkgreen", "Unk" = "darkgray")


pdf("output/Benthic_Relative_Abundance.pdf", width=3, height=4)
RA.plot <- RA.100 %>%
  ggplot(aes(x = Site, y = freq, fill = Label)) +
  geom_col() +
  scale_fill_manual(values = colors)+
  theme_bw() +
  ylab("Relative Abundance") +
  xlab("Site")
RA.plot
dev.off()

```

keep only corals for analysis
```{r}
# Define the labels to filter out
labels_to_exclude <- c("AlgalTurf",   "D_coral", "Halimeda",  "MAL", "Sand", "Tur_orn", "Unk")

# Filter the dataframe to exclude the specified labels
RA.100_filtered <- data.subset %>%
  filter(!Label %in% labels_to_exclude)

Cor.RA <- RA.100_filtered %>%
  group_by(Label) %>%
  summarise(Count = n()) %>% 
  mutate(freq=Count/sum(Count))
Cor.RA$Site <- "Manava"

pdf("output/Coral_Relative_Abundance.pdf", width=3, height=4)
RA.Cor.plot <- Cor.RA %>%
  ggplot(aes(x = Site, y = freq, fill = Label)) +
  geom_col() +
  scale_fill_manual(values = colors)+
  theme_bw() +
  ylab("Relative Abundance") +
  xlab("Site")
RA.Cor.plot 
dev.off()

```



```{r}
#this one looks good

#T3 <- data %>% filter(str_detect(Name, "T3"))
#T3$Name <- gsub("TPC_poc_transect_3TPC_", "", T3$Name)
#T3 <- T3 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))
#counts <- T3 %>%
#  group_by(Transect, Quad) %>%
#  summarise(Count = n()) 
#quadrat 00 is doubled
#quadrat 36 is doubled

#T4 <- data %>% filter(str_detect(Name, "T4"))
#T4$Name <- gsub("TPC_poc_Transect_4TPC_", "", T4$Name)
#T4 <- T4 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))
#counts <- T4 %>%
#  group_by(Transect, Quad) %>%
#  summarise(Count = n()) 
#quadrat 38 is doubled

#T5 <- data %>% filter(str_detect(Name, "TPC_poc_Transect_5TPC_Q"))
#T5$Name <- gsub("TPC_poc_Transect_5TPC_", "", T5$Name)
#T5 <- T5 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))
#counts <- T5 %>%
#  group_by(Transect, Quad) %>%
#  summarise(Count = n()) 
#quadrat 00 is 4 times
#quadrat 10 is doubled
#quadrat 16 is doubled
#quadrat 18 is doubled
#quadrat 20 is doubled
#quadrat 22 is doubled
#quadrat 26 is doubled

#T6 <- data %>% filter(str_detect(Name, "T6"))
#T6$Name <- gsub("TPC_poc_Transect_6TPC_", "", T6$Name)
#T6 <- T6 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))
#counts <- T6 %>%
#  group_by(Transect, Quad) %>%
#  summarise(Count = n()) 
#quadrat 00 is missing
#quadrat 02 is missing

```



```{r}
#Data with 30 points
data$Name <- gsub("TPC_Transect_1TPC_", "", data$Name)
data$Name <- gsub("TPC_Quadrats_transect_2TPC_", "", data$Name)
data$Name <- gsub("TPC_poc_transect_3TPC_", "", data$Name)
data$Name <- gsub("TPC_poc_Transect_4TPC_", "", data$Name)
data$Name <- gsub("TPC_poc_Transect_6TPC_", "", data$Name)
data$Name <- gsub("TPC_poc_Transect_5TPC_", "", data$Name)
data$Name <- gsub("TPC_poc_TransectTPC_", "", data$Name)
data$Name <- gsub("TPC_TPC_", "", data$Name)
data$Name <- gsub("TPC_", "", data$Name)


#split first column into metadata
data <- data %>% separate(Name, c("Quad", "Site", "Transect", "Num"))


counts <- data %>%
  group_by(Transect, Quad) %>%
  summarise(Count = n()) 

#data with 50 points
data_2$Name <- gsub("TPC_Transect_1TPC_", "", data_2$Name)
data_2$Name <- gsub("TPC_Quadrats_transect_2TPC_", "", data_2$Name)
data_2$Name <- gsub("TPC_poc_TransectTPC_", "", data_2$Name)
data_2$Name <- gsub("TPC_TPC_", "", data_2$Name)
data_2$Name <- gsub("TPC_", "", data_2$Name)

#split first column into metadata
data_2 <- data_2 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))


counts <- data_2 %>%
  group_by(Transect, Quad) %>%
  summarise(Count = n()) 


#data with 100 points
data_3$Name <- gsub("100_TPC_", "", data_3$Name)

#split first column into metadata
data_3 <- data_3 %>% separate(Name, c("Quad", "Site", "Transect", "Num"))

counts <- data_3 %>%
  group_by(Transect, Quad) %>%
  summarise(Count = n()) 

```

```{r}

T2.RA <- T2 %>%
  group_by(Label) %>%
  summarise(Count = n()) %>% 
  mutate(freq=Count/sum(Count))
T2.RA$Transect <- "Transect 2"

colors <- c("Acropora"="yellow",   "D_coral" = "gray",    "MACR_Cal_H" ="green",  "MAL"="lightgreen", "Monti"="purple", 
            "Pocillopor" = "coral", "Por Mass D" = "lightyellow", "Porites" ="brown", "Sand"= "tan", "Turbin" = "darkgreen",
            "Turf" = "cyan", "UOth" = "black", "UnkMacroa" = "blue",  "Unkn coral" = "darkgray")

T2.RA.plot <- T2.RA %>%
  ggplot(aes(x = Transect, y = freq, fill = Label)) +
  geom_col() +
  scale_fill_manual(values = colors)+
  theme_bw() +
  ylab("Relative Abundance") +
  xlab("Transect")
T2.RA.plot



```
keep only corals for analysis
```{r}
# Define the labels to filter out
labels_to_exclude <- c("D_coral", "MACR_Cal_H", "MAL", "Por Mass D", "Sand", "Turbin", "Turf", "UOth", "UnkMacroa")

# Filter the dataframe to exclude the specified labels
T2_filtered <- T2 %>%
  filter(!Label %in% labels_to_exclude)


T2.Cor.RA <- T2_filtered %>%
  group_by(Label) %>%
  summarise(Count = n()) %>% 
  mutate(freq=Count/sum(Count))
T2.Cor.RA$Transect <- "Transect 2"

T2.RA.Cor.plot <- T2.Cor.RA %>%
  ggplot(aes(x = Transect, y = freq, fill = Label)) +
  geom_col() +
  scale_fill_manual(values = colors)+
  theme_bw() +
  ylab("Relative Abundance") +
  xlab("Transect")
T2.RA.Cor.plot 


```

```{r}
#data with 100 points
T2_100.RA <- T2 %>%
  group_by(Label) %>%
  summarise(Count = n()) %>% 
  mutate(freq=Count/sum(Count))
T2_100.RA$Transect <- "Transect 2"

colors <- c("Acropora"="yellow",   "D_coral" = "gray",    "MACR_Cal_H" ="green",  "MAL"="lightgreen", "Monti"="purple", 
            "Pocillopor" = "coral", "Por Mass D" = "lightyellow", "Porites" ="brown", "Sand"= "tan", "Turbin" = "darkgreen",
            "Turf" = "cyan", "UOth" = "black", "UnkMacroa" = "blue",  "Unkn coral" = "darkgray")

T2_100.RA.plot <- T2_100.RA %>%
  ggplot(aes(x = Transect, y = freq, fill = Label)) +
  geom_col() +
  scale_fill_manual(values = colors)+
  theme_bw() +
  ylab("Relative Abundance") +
  xlab("Transect")
T2_100.RA.plot

```
```


RA.manava.plot_species <- ggplot(relative_abundance.manava, aes(x = Transect, y = Relative_Abundance, fill = Species.ID)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_wrap(~ SizeClass, ncol = 5) +
  labs(x = "Transect",
       y = "Relative Abundance") +
  theme_minimal() +  # Clean theme
  scale_y_continuous(labels = scales::percent) +  # Convert y-axis to percentage
  scale_fill_manual(values = cols.species) +  # Set the fill colors
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top") +
  
  # Add sample size text
#  geom_text(data = sample_sizes_manava, aes(x = Transect, y = 1.1, label = Sample_Size),
#            inherit.aes = FALSE, size = 2, vjust = 0, color = "black")

RA.manava.plot_species





```

```{r}
#
```




